CREATE TABLE [dbo].[People]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[FirstName] VARCHAR(255) NOT NULL,
	[LastName] VARCHAR(255) NOT NULL,
	[Age] INT NOT NULL,
	[Interests] NVARCHAR(255),
	[Image] NVARCHAR(255),
	[Test] VARCHAR(5),
)
